name: Java CI with Maven and Automatic PR Merge

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean verify
      
  auto-merge:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
    
    steps:
    - name: Auto Merge
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const { owner, repo } = context.repo;
          const pullNumber = context.issue.number;
          
          const { data: prChecks } = await github.rest.checks.listForRef({
            owner,
            repo,
            ref: context.payload.pull_request.head.sha
          });
          
          const allChecksPassed = prChecks.check_runs.every(
            check => check.conclusion === 'success'
          );
          
          const { data: prDetails } = await github.rest.pulls.get({
            owner,
            repo,
            pull_number: pullNumber
          });
          
          const canBeMerged = prDetails.mergeable && allChecksPassed;
          
          if (canBeMerged) {
            await github.rest.pulls.merge({
              owner,
              repo,
              pull_number: pullNumber,
              merge_method: 'squash'
            });
            
            console.log(`Automatically merged PR #${pullNumber}`);
          } else {
            console.log(`PR #${pullNumber} cannot be merged automatically`);
          }
